---
swagger: "2.0"
info:
  description: This is a simple API
  version: 1.0.0
  title: Peduli Covid API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: virtserver.swaggerhub.com
basePath: /rifqinafis/PeduliCovid/1.0.0
tags:
- name: developers
  description: Operations available to regular developers
schemes:
- https
paths:
  /province:
    get:
      tags:
      - developers
      summary: Get All Province Data
      description: |
        By passing in the appropriate options, you can search for province data
      operationId: getAllProvince
      produces:
      - application/json
      parameters: []
      responses:
        "200":
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/Province'
        "400":
          description: bad input parameter
  /city:
    get:
      tags:
      - developers
      summary: Get All City Data By Province
      description: |
        By passing in the appropriate options, you can search for city data
      operationId: getAllCity
      produces:
      - application/json
      parameters:
      - name: provinceId
        in: query
        description: enter province id
        required: true
        type: integer
      responses:
        "200":
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/City'
        "400":
          description: bad input parameter
  /hospital:
    get:
      tags:
      - developers
      summary: Get All Hospital Data By City
      description: |
        By passing in the appropriate options, you can search for hospital data
      operationId: getAllHospital
      produces:
      - application/json
      parameters:
      - name: cityId
        in: query
        description: enter city id
        required: true
        type: integer
      - name: type
        in: query
        description: type=1 for covid, type=2 for non-covid
        required: true
        type: integer
      responses:
        "200":
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/Hospital'
        "400":
          description: bad input parameter
  /bed-type/{id}:
    get:
      tags:
      - developers
      summary: Get Bed Type By Hospital ID
      description: |
        By passing in the appropriate options, you can search for bed type data
      operationId: getBedType
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        description: enter hospital id
        required: true
        type: integer
      - name: type
        in: query
        description: type=1 for covid, type=2 for non-covid
        required: true
        type: integer
      responses:
        "200":
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/BedType'
        "400":
          description: bad input parameter
  /hospital-map/{id}:
    get:
      tags:
      - developers
      summary: Get Detail Hospital Map Data By ID
      description: |
        By passing in the appropriate options, you can search for hospital data
      operationId: getDetailHospitalMap
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        description: enter hospital id
        required: true
        type: integer
      responses:
        "200":
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/HospitalMap'
        "400":
          description: bad input parameter
  /reservation:
    post:
      tags:
      - developers
      summary: Post Reservation
      description: |
        By passing in the appropriate options, you can reservation a bed
      operationId: postReservation
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: User to reservation bed
        required: false
        schema:
          $ref: '#/definitions/body'
      responses:
        "200":
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/Reservation'
        "400":
          description: bad input parameter
  /payment/{id}:
    post:
      tags:
      - developers
      summary: Post Payment
      description: |
        By passing in the appropriate options, you can pay your reservation
      operationId: postPayment
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        description: enter payment id
        required: true
        type: integer
      - in: body
        name: body
        description: User to pay reservation
        required: false
        schema:
          $ref: '#/definitions/body_1'
      responses:
        "200":
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/Payment'
        "400":
          description: bad input parameter
definitions:
  Province:
    type: object
    required:
    - data
    - meta
    - msg
    - stat
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/Province_data'
      meta:
        type: string
      stat:
        type: integer
        example: 200
      msg:
        type: string
        example: success
  City:
    type: object
    required:
    - data
    - meta
    - msg
    - stat
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/City_data'
      meta:
        type: string
      stat:
        type: integer
        example: 200
      msg:
        type: string
        example: success
  Hospital:
    type: object
    required:
    - data
    - meta
    - msg
    - stat
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/Hospital_data'
      meta:
        type: string
      stat:
        type: integer
        example: 200
      msg:
        type: string
        example: success
  BedType:
    type: object
    required:
    - data
    - meta
    - msg
    - stat
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/BedType_data'
      meta:
        type: string
      stat:
        type: integer
        example: 200
      msg:
        type: string
        example: success
  HospitalMap:
    type: object
    required:
    - data
    - meta
    - msg
    - stat
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/HospitalMap_data'
      meta:
        type: string
      stat:
        type: integer
        example: 200
      msg:
        type: string
        example: success
  Reservation:
    type: object
    required:
    - data
    - meta
    - msg
    - stat
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/Reservation_data'
      meta:
        type: string
      stat:
        type: integer
        example: 200
      msg:
        type: string
        example: success
  Payment:
    type: object
    required:
    - data
    - meta
    - msg
    - stat
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/Payment_data'
      meta:
        type: string
      stat:
        type: integer
        example: 200
      msg:
        type: string
        example: success
  body:
    type: object
    required:
    - bedTypeId
    - hospitalId
    properties:
      hospitalId:
        type: integer
      bedTypeId:
        type: integer
  body_1:
    type: object
    required:
    - amount
    - paymentMethodId
    properties:
      paymentMethodId:
        type: integer
      amount:
        type: number
  Province_data:
    type: object
    properties:
      id:
        type: string
        format: serial
        example: "1"
      code:
        type: string
        example: 1prop
      name:
        type: string
        example: Jawa Timur
      createdAt:
        type: string
        format: date-time
        example: 2016-08-29 T09:12:33.001Z
      updatedAt:
        type: string
        format: date-time
        example: 2016-08-29 T09:12:33.001Z
  City_data:
    type: object
    properties:
      id:
        type: string
        format: serial
        example: "1"
      provinceId:
        type: integer
        format: serial
        example: 1
      code:
        type: string
        example: SBY
      name:
        type: string
        example: Surabaya
      createdAt:
        type: string
        format: date-time
        example: 2016-08-29 T09:12:33.001Z
      updatedAt:
        type: string
        format: date-time
        example: 2016-08-29 T09:12:33.001Z
  Hospital_data:
    type: object
    properties:
      id:
        type: string
        format: serial
        example: "1"
      cityId:
        type: integer
        format: serial
        example: 1
      name:
        type: string
        example: RS dr. Ramelan
      phone:
        type: string
        example: 3.18404062E8
      address:
        type: string
        example: Jl. Gadung No. 1 Surabaya
      bedAvailable:
        type: integer
        example: 10
      createdAt:
        type: string
        format: date-time
        example: 2016-08-29 T09:12:33.001Z
      updatedAt:
        type: string
        format: date-time
        example: 2016-08-29 T09:12:33.001Z
  BedType_data:
    type: object
    properties:
      id:
        type: string
        format: serial
        example: "1"
      hospitalId:
        type: integer
        format: serial
        example: 1
      name:
        type: string
        example: IGD Khusus Covid
      bedEmpty:
        type: integer
        example: 10
      bedAvailable:
        type: integer
        example: 10
      createdAt:
        type: string
        format: date-time
        example: 2016-08-29 T09:12:33.001Z
      updatedAt:
        type: string
        format: date-time
        example: 2016-08-29 T09:12:33.001Z
  HospitalMap_data:
    type: object
    properties:
      id:
        type: string
        format: serial
        example: "1"
      name:
        type: string
        example: RS dr. Ramelan
      address:
        type: string
        example: Jl. Gadung No. 1 Surabaya
      link:
        type: string
        example: https://www.google.com/maps/search/?api=1&query=-7.3083,112.738
      createdAt:
        type: string
        format: date-time
        example: 2016-08-29 T09:12:33.001Z
      updatedAt:
        type: string
        format: date-time
        example: 2016-08-29 T09:12:33.001Z
  Reservation_data:
    type: object
    properties:
      id:
        type: string
        format: serial
        example: "1"
      paymentId:
        type: string
        format: serial
        example: "1"
      amount:
        type: number
        example: 300123.0
      createdAt:
        type: string
        format: date-time
        example: 2016-08-29 T09:12:33.001Z
      updatedAt:
        type: string
        format: date-time
        example: 2016-08-29 T09:12:33.001Z
  Payment_data:
    type: object
    properties:
      id:
        type: string
        format: serial
        example: "1"
      paymentMethodId:
        type: string
        format: serial
        example: "1"
      reservationId:
        type: string
        format: serial
        example: "1"
      amount:
        type: number
        example: 300123.0
      date:
        type: string
        format: date-time
        example: 2016-08-29 T09:12:33.001Z
      createdAt:
        type: string
        format: date-time
        example: 2016-08-29 T09:12:33.001Z
      updatedAt:
        type: string
        format: date-time
        example: 2016-08-29 T09:12:33.001Z
